# Recsystem Movies

## Dataset

In [22]:
## Dataset 
! pip install pandas

Requirement already satisfied: pandas in c:\Users\vanessa34180026\TRASNFORMEDIGITAL\.venv\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\vanessa34180026\TRASNFORMEDIGITAL\.venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\vanessa34180026\TRASNFORMEDIGITAL\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\vanessa34180026\TRASNFORMEDIGITAL\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\vanessa34180026\TRASNFORMEDIGITAL\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [23]:
import pandas as pd

In [24]:
df_movies = pd.read_csv('datasets/movies.csv')

criando depois uma celular par amudar a coluna  isso foi feito depois edo ratings , volta mos para tras

In [25]:
df_movies.columns = ['id_filme', 'titulo', 'genero']

In [26]:
df_movies = df_movies.set_index('id_filme')

In [27]:
df_movies.head()

,titulo,genero
id_filme,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

In [28]:
df_movies.head()

,titulo,genero
id_filme,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

Carregamento o dataframe de notas

In [29]:
df_ratings = pd.read_csv('datasets/ratings.csv')

In [30]:
df_ratings.columns = ['id_usuari','id_filme', 'nota', 'timestep']

In [31]:
print(df_movies.columns.tolist())

['titulo', 'genero']

In [32]:
df_ratings.head()

   id_usuari  id_filme  nota   timestep
0          1         1   4.0  964982703
1          1         3   4.0  964981247
2          1         6   4.0  964982224
3          1        47   5.0  964983815
4          1        50   5.0  964982931

In [33]:
df_ratings.describe()

           id_usuari       id_filme           nota      timestep
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

df_ratings.

Primeira recomandação

In [36]:
df_ratings['id_filme'].value_counts().head(3)

id_filme
356    329
318    317
296    307
Name: count, dtype: int64

In [37]:
df_movies.loc[356]

titulo         Forrest Gump (1994)
genero    Comedy|Drama|Romance|War
Name: 356, dtype: str

In [39]:
# total de votos 
total_votos = df_ratings['id_filme'].value_counts()
total_votos.head()

id_filme
356     329
318     317
296     307
593     279
2571    278
Name: count, dtype: int64

In [49]:
df_movies['total_votos'] = total_votos

In [50]:
df_movies.head()

,titulo,genero,total-votos,total_votos
id_filme,,,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,215.0,215.0
2,Jumanji (1995),Adventure|Children|Fantasy,110.0,110.0
3,Grumpier Old Men (1995),Comedy|Romance,52.0,52.0
4,Waiting to Exhale (1995),Comedy|Drama|Romance,7.0,7.0
5,Father of the Bride Part II (1995),Comedy,49.0,49.0

In [51]:
df_ratings.head(3)

   id_usuari  id_filme  nota   timestep
0          1         1   4.0  964982703
1          1         3   4.0  964981247
2          1         6   4.0  964982224

In [52]:
# funcao  de ordernar cresente 
df_movies.sort_values('total_votos', ascending=False).head(10)

,titulo,genero,total-votos,total_votos
id_filme,,,,
356,Forrest Gump (1994),Comedy|Drama|Romance|War,329.0,329.0
318,"Shawshank Redemption, The (1994)",Crime|Drama,317.0,317.0
296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,307.0,307.0
593,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,279.0,279.0
2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller,278.0,278.0
260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,251.0,251.0
480,Jurassic Park (1993),Action|Adventure|Sci-Fi|Thriller,238.0,238.0
110,Braveheart (1995),Action|Drama|War,237.0,237.0
589,Terminator 2: Judgment Day (1991),Action|Sci-Fi,224.0,224.0
527,Schindler's List (1993),Drama|War,220.0,220.0

In [53]:

os_tres_indicados = df_movies.sort_values('total_votos', ascending=False).head(3)
os_tres_indicados

,titulo,genero,total-votos,total_votos
id_filme,,,,
356,Forrest Gump (1994),Comedy|Drama|Romance|War,329.0,329.0
318,"Shawshank Redemption, The (1994)",Crime|Drama,317.0,317.0
296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,307.0,307.0